### ISSUE TITLE
Hydrogen compatibility

### ISSUE THREAD

**Issue by piccolbo** [yhat/ggpy#601]
I am trying to use ggplot2 with hydrogen for inline graphics on the atom editor. Plots appear to the right of code, covering following lines of code and truncating the x axis out. Granted I have no clue whether this is a problem in ggplot or hydrogen, but if you could give me a hint where to look, parameters to tweak and what not, maybe I can provide feedback here or to the hydrogen folks. Thanks

**Comment by potocpav** [comment]
workaround for the plots to not appear to the right: use 
`(ggplot(..) + geom_line() + ...).show()` 
instead of just 
`ggplot(..) + geom_line() + ...`

Workaround for the second issue where the graph is not shown completely: add the following to your Atom stylesheet (Edit -> Stylesheet):

```css
.hydrogen.output-bubble {
  .bubble-output-container {
    max-height: 1000px !important;
  }
}
```

With these, I can use Hydrogen with ggpy fine
